version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    container_name: fastapi
    image: justkacz/fastapi:1.0
    ports:
      - "8000:8000"
    # volumes:
    #   - ./web:/app
    networks:
      - fastapinet

    environment:
      - FLASK_ENV=development

  db:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - fastapinet
    volumes:
      - mongodbdata:/data/db

  

networks:
  fastapinet:

volumes:
  mongodbdata:
    driver: local