version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    container_name: fastapi
    image: justkacz/fastapi
    depends_on:
      - db
    pull_policy: build
    ports:
      - "8000:8000"
    volumes: # to make changes visible without image removal
      - ./web:/web
    networks:
      - fastapinet

    environment:
      - FLASK_ENV=development

  db:
    image: mongo:5.0.0
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - fastapinet
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=booksdb
    volumes:
      - ./web/db/scripts:/docker-entrypoint-initdb.d/seed.js # add data when container is initialized
      - mongodbdata:/data/db

  

networks:
  fastapinet:

volumes:
  mongodbdata:
    driver: local